// ABOUTME: Generates seed SQL from courses.json for D1.
// ABOUTME: Uses UPSERT to sync catalog data without disrupting runtime state.
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Seed script for D1. Generates an idempotent SQL file from courses.json.
 *
 * Uses INSERT ... ON CONFLICT to update catalog fields (name, city, platform,
 * platform_config, booking_url) without touching runtime-managed fields
 * (is_active, last_had_tee_times). New courses get is_active=1 from the
 * column default.
 *
 * Generate: npx tsx scripts/seed.ts
 * Apply locally: npx wrangler d1 execute tee-times-db --local --file=scripts/seed.sql
 * Apply remote: npx wrangler d1 execute tee-times-db --remote --file=scripts/seed.sql
 */

interface CourseEntry {
  id: string;
  name: string;
  city: string;
  state?: string;
  disabled?: number;
  displayNotes?: string;
  platform: string;
  platformConfig: Record<string, string>;
  bookingUrl: string;
}

const coursesPath = resolve(__dirname, "../src/config/courses.json");
const courses: CourseEntry[] = JSON.parse(readFileSync(coursesPath, "utf-8"));

const esc = (s: string) => s.replace(/'/g, "''");

const lines: string[] = [
  "-- Auto-generated by scripts/seed.ts — do not edit manually",
  "-- Uses UPSERT: updates catalog fields, preserves runtime state (is_active, last_had_tee_times, display_notes unless explicitly set in JSON)",
  "",
];

for (const course of courses) {
  const displayNotesVal = course.displayNotes ? `'${esc(course.displayNotes)}'` : "NULL";
  // Only overwrite display_notes on conflict when the JSON explicitly sets it.
  // Otherwise, preserve dynamically-set DB values (e.g. seasonal closure notes from cron).
  const updateCols = [
    "name=excluded.name",
    "city=excluded.city",
    "state=excluded.state",
    "disabled=excluded.disabled",
    "platform=excluded.platform",
    "platform_config=excluded.platform_config",
    "booking_url=excluded.booking_url",
  ];
  if (course.displayNotes) {
    updateCols.splice(4, 0, "display_notes=excluded.display_notes");
  }
  lines.push(
    `INSERT INTO courses (id, name, city, state, disabled, display_notes, platform, platform_config, booking_url) VALUES ('${esc(course.id)}', '${esc(course.name)}', '${esc(course.city)}', '${esc(course.state ?? "MN")}', ${course.disabled ?? 0}, ${displayNotesVal}, '${esc(course.platform)}', '${esc(JSON.stringify(course.platformConfig))}', '${esc(course.bookingUrl)}') ON CONFLICT(id) DO UPDATE SET ${updateCols.join(", ")};`
  );
}

const outputPath = resolve(__dirname, "seed.sql");
writeFileSync(outputPath, lines.join("\n") + "\n");
console.log(`Wrote ${courses.length} courses to ${outputPath}`);
