-- Auto-generated by scripts/seed.ts — do not edit manually
DELETE FROM tee_times;
DELETE FROM poll_log;
DELETE FROM courses;

INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('theodore-wirth-18', 'Theodore Wirth', 'Minneapolis', 'cps_golf', '{"subdomain":"minneapolistheodorewirth","apiKey":"8ea2914e-cac2-48a7-a3e5-e0f41350bf3a","courseIds":"17","websiteId":"8265e495-5c83-44e5-93d8-c9e3f3a40529"}', 'https://minneapolistheodorewirth.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('gross-national', 'Gross National', 'Minneapolis', 'cps_golf', '{"subdomain":"minneapolisgrossnational"}', 'https://minneapolisgrossnational.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('meadowbrook', 'Meadowbrook', 'Minneapolis', 'cps_golf', '{"subdomain":"minneapolismeadowbrook"}', 'https://minneapolismeadowbrook.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('columbia', 'Columbia', 'Minneapolis', 'cps_golf', '{"subdomain":"minneapoliscolumbia"}', 'https://minneapoliscolumbia.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('hiawatha', 'Hiawatha', 'Minneapolis', 'cps_golf', '{"subdomain":"minneapolishiawatha"}', 'https://minneapolishiawatha.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('phalen', 'Phalen', 'St. Paul', 'cps_golf', '{"subdomain":"phalen"}', 'https://phalen.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('chaska-town-course', 'Chaska Town Course', 'Chaska', 'cps_golf', '{"subdomain":"chaska"}', 'https://chaska.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('edinburgh-usa', 'Edinburgh USA', 'Brooklyn Park', 'cps_golf', '{"subdomain":"edinburghusa"}', 'https://edinburghusa.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('oak-glen', 'Oak Glen', 'Stillwater', 'cps_golf', '{"subdomain":"oakglen"}', 'https://oakglen.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('highland-national', 'Highland National', 'St. Paul', 'cps_golf', '{"subdomain":"highlandnationalmn"}', 'https://highlandnationalmn.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('como-park', 'Como Park', 'St. Paul', 'cps_golf', '{"subdomain":"como"}', 'https://como.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('victory-links', 'Victory Links', 'Blaine', 'cps_golf', '{"subdomain":"victorylinksmn"}', 'https://victorylinksmn.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('gem-lake-hills', 'Gem Lake Hills', 'White Bear Lake', 'cps_golf', '{"subdomain":"gem"}', 'https://gem.cps.golf/onlineresweb', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('braemar', 'Braemar', 'Edina', 'foreup', '{"facilityId":"21445","scheduleId":"7829"}', 'https://foreupsoftware.com/index.php/booking/21445/7829', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('bunker-hills', 'Bunker Hills', 'Coon Rapids', 'foreup', '{"facilityId":"20252"}', 'https://foreupsoftware.com/index.php/booking/20252', 1);
INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('roseville-cedarholm', 'Roseville Cedarholm', 'Roseville', 'foreup', '{"facilityId":"22244","scheduleId":"10216"}', 'https://foreupsoftware.com/index.php/booking/22244/10216', 1);
