import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Seed script for D1. Run with:
 *   npx wrangler d1 execute tee-times-db --local --file=scripts/seed.sql
 *
 * This script generates the SQL file from courses.json.
 * Run: npx tsx scripts/seed.ts
 */

interface CourseEntry {
  id: string;
  name: string;
  city: string;
  platform: string;
  platformConfig: Record<string, string>;
  bookingUrl: string;
}

const coursesPath = resolve(__dirname, "../src/config/courses.json");
const courses: CourseEntry[] = JSON.parse(readFileSync(coursesPath, "utf-8"));

const lines: string[] = [
  "-- Auto-generated by scripts/seed.ts — do not edit manually",
  "DELETE FROM tee_times;",
  "DELETE FROM poll_log;",
  "DELETE FROM courses;",
  "",
];

for (const course of courses) {
  const esc = (s: string) => s.replace(/'/g, "''");
  lines.push(
    `INSERT INTO courses (id, name, city, platform, platform_config, booking_url, is_active) VALUES ('${esc(course.id)}', '${esc(course.name)}', '${esc(course.city)}', '${esc(course.platform)}', '${esc(JSON.stringify(course.platformConfig))}', '${esc(course.bookingUrl)}', 1);`
  );
}

const outputPath = resolve(__dirname, "seed.sql");
writeFileSync(outputPath, lines.join("\n") + "\n");
console.log(`Wrote ${courses.length} courses to ${outputPath}`);
